export const sampleStocks = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 150.25,
    change: 1.5 >= 0 ? `+${1.5}` : `${1.5}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "BUY",
      timeframe: "10 days",
      reason: "Strong product pipeline and upcoming iPhone release cycle",
    },
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 2750.8,
    change: -0.8 >= 0 ? `+${-0.8}` : `${-0.8}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "SELL",
      timeframe: "tomorrow",
      reason: "Increasing competition in AI space and regulatory pressures",
    },
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 305.5,
    change: 0.6 >= 0 ? `+${0.6}` : `${0.6}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 3380.2,
    change: -1.2 >= 0 ? `+${-1.2}` : `${-1.2}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "FB",
    name: "Meta Platforms Inc.",
    price: 330.15,
    change: 2.1 >= 0 ? `+${2.1}` : `${2.1}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 780.9,
    change: 3.5 >= 0 ? `+${3.5}` : `${3.5}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 220.75,
    change: 1.8 >= 0 ? `+${1.8}` : `${1.8}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 160.4,
    change: -0.5 >= 0 ? `+${-0.5}` : `${-0.5}`,
    sector: "Financial",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    price: 230.8,
    change: 0.9 >= 0 ? `+${0.9}` : `${0.9}`,
    sector: "Financial",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    price: 170.6,
    change: 0.3 >= 0 ? `+${0.3}` : `${0.3}`,
    sector: "Healthcare",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    price: 145.3,
    change: -0.2 >= 0 ? `+${-0.2}` : `${-0.2}`,
    sector: "Consumer Defensive",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    price: 140.9,
    change: 0.7 >= 0 ? `+${0.7}` : `${0.7}`,
    sector: "Consumer Defensive",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "MA",
    name: "Mastercard Inc.",
    price: 355.7,
    change: 1.1 >= 0 ? `+${1.1}` : `${1.1}`,
    sector: "Financial",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Inc.",
    price: 410.2,
    change: -0.4 >= 0 ? `+${-0.4}` : `${-0.4}`,
    sector: "Healthcare",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "HD",
    name: "The Home Depot Inc.",
    price: 330.5,
    change: 0.8 >= 0 ? `+${0.8}` : `${0.8}`,
    sector: "Consumer Cyclical",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    price: 175.8,
    change: -1.5 >= 0 ? `+${-1.5}` : `${-1.5}`,
    sector: "Consumer Cyclical",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc.",
    price: 550.4,
    change: 2.3 >= 0 ? `+${2.3}` : `${2.3}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "CRM",
    name: "Salesforce.com Inc.",
    price: 260.3,
    change: 1.6 >= 0 ? `+${1.6}` : `${1.6}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    price: 590.7,
    change: -0.9 >= 0 ? `+${-0.9}` : `${-0.9}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "PYPL",
    name: "PayPal Holdings Inc.",
    price: 270.5,
    change: 1.2 >= 0 ? `+${1.2}` : `${1.2}`,
    sector: "Technology",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
  {
    symbol: "ADS",
    name: "Adidas AG",
    price: 108.49,
    change: 11.83 >= 0 ? `+${11.83}` : `${11.83}`,
    sector: "Consumer Goods",
    marketCap: "Large Cap",
    recommendation: {
      action: "HOLD",
      timeframe: "now",
      reason: "Stable cloud growth but current valuation is fair",
    },
  },
]

export const sampleOHLCData = {
  GOOGL: [
    { time: "2023-06-01", open: 2700, high: 2750, low: 2680, close: 2730 },
    { time: "2023-06-02", open: 2730, high: 2780, low: 2710, close: 2760 },
    { time: "2023-06-05", open: 2760, high: 2800, low: 2740, close: 2790 },
    { time: "2023-06-06", open: 2790, high: 2820, low: 2770, close: 2810 },
    { time: "2023-06-07", open: 2810, high: 2840, low: 2790, close: 2830 },
  ],
  NVDA: [
    { time: "2023-06-01", open: 210, high: 215, low: 208, close: 213 },
    { time: "2023-06-02", open: 213, high: 218, low: 211, close: 216 },
    { time: "2023-06-05", open: 216, high: 220, low: 214, close: 219 },
    { time: "2023-06-06", open: 219, high: 223, low: 217, close: 221 },
    { time: "2023-06-07", open: 221, high: 225, low: 219, close: 223 },
  ],
}

export const userPortfolio = {
  NVDA: 10,
  AAPL: 5,
  MSFT: 8,
}
